(() => {
  const copy = {
    en: {
"Ver ferramentas": "See tools",
"OFERTA ÚNICA DE LANÇAMENTO": "EXCLUSIVE LAUNCH OFFER",
"Seu próximo passo começa aqui": "Your next step starts here",
"Você está pronto para": "Are you ready to",
"mudar totalmente": "completely change",
"a forma de detalhar projetos no Revit?": "the way you detail projects in Revit?",
"Menos repetição.": "Less repetition.",
"Mais possibilidades.": "More possibilities.",
"Role para decolar": "Scroll to lift off",

"Mais tempo para": "More time to",
"projetar.": "design.",
"Menos tempo para repetir.": "Less time repeating.",
"Cotas, vistas, tags e pranchas com poucos cliques.": "Dimensions, views, tags, and sheets in a few clicks.",
"Seu projeto avança. Sua documentação acompanha.": "Your project moves forward. Your documentation keeps up.",
"Do projeto à documentação": "From design to documentation",
"Dentro do Revit. No seu projeto.": "Inside Revit. In your project.",
"Veja o DocFlow": "See DocFlow",
"em ação.": "in action.",
"Escolha uma ferramenta. Veja a documentação acontecer.": "Choose a tool. Watch the documentation take shape.",

      "Quero documentar em poucos cliques": "I want to document in a few clicks",
      "Documentação de arquitetura dentro do Revit": "Architecture documentation inside Revit",
      "O fim das": "The end of", "cotas e detalhamentos manuais": "manual dimensions and detailing", "de arquitetura": "in architecture",
      "Gere cotas, vistas e pranchas no Revit com poucos cliques.": "Create dimensions, views, and sheets in Revit with just a few clicks.",
      "Ganhe tempo para projetar e focar no que realmente importa.": "Save time to design and focus on what really matters.",
      "Projeto arquitetônico — Autodesk Revit": "Architectural project — Autodesk Revit", "Arquivo": "File", "Arquitetura": "Architecture", "Estrutura": "Structure", "Inserir": "Insert", "Anotar": "Annotate", "Vista": "View", "Modificar": "Modify", "EM AÇÃO": "IN ACTION", "Cotas": "Dimensions", "Vistas": "Views", "Pranchas": "Sheets", "Tags": "Tags", "Tags em segundos": "Tags in seconds", "Tags automáticas": "Automatic tags", "Identifique portas, janelas, paredes e ambientes com mais agilidade.": "Identify doors, windows, walls, and rooms more quickly.", "Execute o comando e confira as tags prontas no modelo.": "Run the command and review the tags ready in the model.", "Planta de piso: Nível 01": "Floor plan: Level 01", "Escala 1:100": "Scale 1:100", "Cotas de paredes em lote": "Batch wall dimensions",
      "A virada de chave": "The turning point", "Detalhamento de arquitetura não deveria ocupar um dia inteiro.": "Architectural detailing should not take up an entire day.", "Deveria ocupar um clique.": "It should take one click.", "Você não foi contratado para repetir o que o modelo já sabe. Foi contratado para projetar, coordenar e tomar decisões.": "You were not hired to repeat what the model already knows. You were hired to design, coordinate, and make decisions.",
      "Para pra pensar...": "Think about it...", "Quanto do seu": "How much of your", "tempo": "time", "vai para tarefas repetitivas e manuais do Revit?": "goes to repetitive, manual Revit tasks?", "Role para descobrir quanto esse tempo representa.": "Scroll to see what that time represents.",
      "Faça a conta com a sua realidade": "Run the numbers for your own reality", "Seu tempo tem valor.": "Your time has value.", "Coloque na conta.": "Put it on the balance sheet.", "Some as horas dedicadas à criação de vistas, às cotas e à montagem de pranchas. Ajuste os valores e veja quanto esse tempo representa no ano.": "Add up the hours spent creating views, dimensions, and sheets. Adjust the values and see what that time represents over a year.", "Horas por semana nessas tarefas": "Hours per week on these tasks", "Valor da sua hora técnica": "Value of your technical hour", "Valor anual das horas informadas": "Annual value of the hours entered", "Estimativa: horas × valor/hora × 48 semanas. Representa o valor desse tempo, não uma economia garantida.": "Estimate: hours × hourly rate × 48 weeks. It represents the value of this time, not guaranteed savings.", "E se a parte repetitiva não precisasse ocupar tanto espaço no seu dia?": "What if the repetitive part did not have to take up so much of your day?", "Veja como o DocFlow entra na sua rotina.": "See how DocFlow fits into your workflow.",
      "A mesma planta. Dois processos.": "The same plan. Two processes.", "Veja a diferença nas cotas": "See the difference in dimensions", "na prática.": "in practice.", "Quanto tempo você levaria para cotar uma planta como essa?": "How long would it take you to dimension a plan like this?", "Compare o processo manual com a execução usando o DocFlow.": "Compare the manual process with doing the same work using DocFlow.", "Pausar vídeos": "Pause videos", "Do início": "From the beginning", "Processo manual": "Manual process", "Cotas feitas à mão": "Dimensions made by hand", "Vídeo acelerado": "Accelerated video", "Selecionar, posicionar e repetir em cada ambiente.": "Select, position, and repeat in every room.", "Tempo no cronômetro": "Time on the clock", "Processo com DocFlow": "Process with DocFlow", "Cotas com poucos cliques": "Dimensions in just a few clicks", "Executar o comando e conferir as cotas prontas no modelo.": "Run the command and review the dimensions ready in the model.", "Ver as outras ferramentas": "See the other tools",
      "Dentro do Revit": "Inside Revit", "Veja a documentação do seu projeto ganhar forma no Revit.": "See your project documentation take shape in Revit.", "Escolha uma ferramenta e acompanhe o DocFlow executando cada etapa no projeto.": "Choose a tool and follow DocFlow through every step in the project.",
      "Um comando. Uma tarefa resolvida.": "One command. One task solved.", "Você clica uma vez...": "You click once...", "e tudo sai pronto.": "and everything comes out ready.", "Arraste para o lado ou use as setas do teclado.": "Drag sideways or use the keyboard arrows.",
      "Recursos incluídos": "Included features", "As ferramentas que acompanham sua documentação.": "The tools that support your documentation.", "Das primeiras cotas à montagem das pranchas. Um conjunto de comandos para diferentes etapas do seu projeto, na mesma aba do Revit.": "From the first dimensions to sheet assembly. A set of commands for different stages of your project, in the same Revit tab.",
      "Paredes externas": "External walls", "Paredes internas": "Internal walls", "Paredes por seleção": "Walls by selection", "Paredes em lote": "Batch walls", "Famílias por região": "Families by region", "Famílias por ambiente": "Families by room", "Cotas por ambiente": "Dimensions by room", "Cotas de pisos": "Floor dimensions", "Cotas de forros": "Ceiling dimensions", "Cotas em cortes": "Section dimensions", "Tags de portas": "Door tags", "Tags de janelas": "Window tags", "Tags de paredes": "Wall tags", "Tags de ambientes": "Room tags", "Tags de forros": "Ceiling tags", "Nível dos ambientes": "Room levels", "Vistas por ambiente": "Views by room", "Gerador de pranchas": "Sheet generator", "Exportar pranchas": "Export sheets", "Configurações de cotas": "Dimension settings", "Configurações de tags": "Tag settings",
      "Configurável para o seu escritório": "Configurable for your office", "Seu padrão de projeto. Seu jeito de documentar.": "Your project standard. Your way of documenting.", "Use os tipos de cotas que já fazem parte do seu projeto, defina os afastamentos e salve suas preferências. A automação segue o padrão que você configura.": "Use the dimension types already in your project, define offsets, and save your preferences. Automation follows the standard you set.", "Configurações": "Settings", "Tipos de cotas, afastamentos e perfis salvos no mesmo lugar.": "Dimension types, offsets, and saved profiles in one place.",
      "Assinatura anual": "Annual subscription", "Cotas, vistas e pranchas no seu próximo projeto.": "Dimensions, views, and sheets in your next project.", "Acesse as ferramentas do DocFlow ARQ e as atualizações durante a assinatura.": "Access DocFlow ARQ tools and updates throughout your subscription.", "NÃO SOU ALUNO": "I AM NOT A STUDENT", "SOU ALUNO BIM CODER": "I AM A BIM CODER STUDENT", "Desconto de lançamento": "Launch discount", "DocFlow ARQ · Anual": "DocFlow ARQ · Annual", "Preço anual regular:": "Regular annual price:", "preço de lançamento": "launch price", "Ferramentas de cotas, vistas e pranchas": "Dimension, view, and sheet tools", "Configurações e modelos de pranchas": "Settings and sheet templates", "Atualizações durante a assinatura": "Updates during the subscription", "Atendimento DocFlow": "DocFlow support", "7 dias de garantia": "7-day guarantee", "Licença individual · ativação pelo e-mail da compra · compatível com Revit 2025 e 2027": "Individual license · activated using the purchase email · compatible with Revit 2025 and 2027",
      "Teste no seu projeto": "Test it in your project", "Experimente as ferramentas no seu projeto por 7 dias.": "Try the tools in your project for 7 days.", "Instale o DocFlow e experimente as ferramentas de cotas, vistas e pranchas em um projeto seu. Se não fizer sentido para sua rotina, solicite o reembolso dentro do prazo de garantia.": "Install DocFlow and try the dimension, view, and sheet tools in one of your projects. If it does not fit your workflow, request a refund within the guarantee period.",
      "Perguntas frequentes": "Frequently asked questions", "Antes de começar seu próximo projeto.": "Before you start your next project.", "Seu próximo projeto": "Your next project", "Dedique mais tempo ao projeto.": "Dedicate more time to the project.", "Resolva as tarefas repetitivas com poucos cliques.": "Solve repetitive tasks with just a few clicks.", "7 dias de garantia · Revit 2025 e 2027 · suporte em português": "7-day guarantee · Revit 2025 and 2027 · support in Portuguese", "Um produto BIM Coder Tecnologia LTDA": "A BIM Coder Tecnologia LTDA product", "Fechar": "Close", "Prévia interna": "Internal preview", "Checkout ainda não conectado": "Checkout not connected yet", "O plano já está pronto na página. Falta apenas inserir o link correspondente da Hotmart antes da publicação.": "The plan is ready on the page. You only need to add the corresponding Hotmart link before publishing.", "Entendi": "Got it", "Desconto de lançamento · aluno": "Launch discount · student", "Desconto de lançamento para aluno BIM Coder: R$ 300 no primeiro ano. Depois, renovação por R$ 797/ano.": "BIM Coder student launch discount: R$ 300 off in the first year. Then renewal is R$ 797/year.", "Desconto de lançamento de R$ 200 no primeiro ano. Depois, renovação por R$ 797/ano.": "Launch discount of R$ 200 in the first year. Then renewal is R$ 797/year.", "Garantir desconto de aluno — R$ 497": "Claim student discount — R$ 497", "Garantir desconto de lançamento — R$ 597": "Claim launch discount — R$ 597"
    },
    es: {
"Ver ferramentas": "Ver herramientas",
"OFERTA ÚNICA DE LANÇAMENTO": "OFERTA ÚNICA DE LANZAMIENTO",
"Seu próximo passo começa aqui": "Su próximo paso empieza aquí",
"Você está pronto para": "¿Está listo para",
"mudar totalmente": "cambiar por completo",
"a forma de detalhar projetos no Revit?": "la forma de detallar proyectos en Revit?",
"Menos repetição.": "Menos repetición.",
"Mais possibilidades.": "Más posibilidades.",
"Role para decolar": "Desplácese para despegar",

"Mais tempo para": "Más tiempo para",
"projetar.": "diseñar.",
"Menos tempo para repetir.": "Menos tiempo repitiendo.",
"Cotas, vistas, tags e pranchas com poucos cliques.": "Cotas, vistas, etiquetas y láminas con pocos clics.",
"Seu projeto avança. Sua documentação acompanha.": "Su proyecto avanza. Su documentación lo acompaña.",
"Do projeto à documentação": "Del proyecto a la documentación",
"Dentro do Revit. No seu projeto.": "Dentro de Revit. En su proyecto.",
"Veja o DocFlow": "Vea DocFlow",
"em ação.": "en acción.",
"Escolha uma ferramenta. Veja a documentação acontecer.": "Elija una herramienta. Vea cómo se crea la documentación.",

      "Quero documentar em poucos cliques": "Quiero documentar con pocos clics", "Documentação de arquitetura dentro do Revit": "Documentación de arquitectura dentro de Revit", "O fim das": "El fin de las", "cotas e detalhamentos manuais": "cotas y detalles manuales", "de arquitetura": "de arquitectura", "Gere cotas, vistas e pranchas no Revit com poucos cliques.": "Genere cotas, vistas y láminas en Revit con pocos clics.", "Ganhe tempo para projetar e focar no que realmente importa.": "Gane tiempo para diseñar y enfocarse en lo que realmente importa.",
      "Projeto arquitetônico — Autodesk Revit": "Proyecto arquitectónico — Autodesk Revit", "Arquivo": "Archivo", "Arquitetura": "Arquitectura", "Estrutura": "Estructura", "Inserir": "Insertar", "Anotar": "Anotar", "Vista": "Vista", "Modificar": "Modificar", "EM AÇÃO": "EN ACCIÓN", "Cotas": "Cotas", "Vistas": "Vistas", "Pranchas": "Láminas", "Tags": "Etiquetas", "Tags em segundos": "Etiquetas en segundos", "Tags automáticas": "Etiquetas automáticas", "Identifique portas, janelas, paredes e ambientes com mais agilidade.": "Identifique puertas, ventanas, muros y ambientes con mayor agilidad.", "Execute o comando e confira as tags prontas no modelo.": "Ejecute el comando y revise las etiquetas listas en el modelo.", "Planta de piso: Nível 01": "Plano de planta: Nivel 01", "Escala 1:100": "Escala 1:100", "Cotas de paredes em lote": "Cotas de muros por lote",
      "A virada de chave": "El cambio de rumbo", "Detalhamento de arquitetura não deveria ocupar um dia inteiro.": "El detalle arquitectónico no debería ocupar un día entero.", "Deveria ocupar um clique.": "Debería ocupar un clic.", "Você não foi contratado para repetir o que o modelo já sabe. Foi contratado para projetar, coordenar e tomar decisões.": "No fue contratado para repetir lo que el modelo ya sabe. Fue contratado para diseñar, coordinar y tomar decisiones.", "Para pra pensar...": "Piénselo...", "Quanto do seu": "¿Cuánto de su", "tempo": "tiempo", "vai para tarefas repetitivas e manuais do Revit?": "se destina a tareas repetitivas y manuales de Revit?", "Role para descobrir quanto esse tempo representa.": "Desplácese para descubrir cuánto representa ese tiempo.",
      "Faça a conta com a sua realidade": "Haga las cuentas según su realidad", "Seu tempo tem valor.": "Su tiempo tiene valor.", "Coloque na conta.": "Téngalo en cuenta.", "Some as horas dedicadas à criação de vistas, às cotas e à montagem de pranchas. Ajuste os valores e veja quanto esse tempo representa no ano.": "Sume las horas dedicadas a crear vistas, cotas y láminas. Ajuste los valores y vea cuánto representa ese tiempo al año.", "Horas por semana nessas tarefas": "Horas por semana en estas tareas", "Valor da sua hora técnica": "Valor de su hora técnica", "Valor anual das horas informadas": "Valor anual de las horas informadas", "Estimativa: horas × valor/hora × 48 semanas. Representa o valor desse tempo, não uma economia garantida.": "Estimación: horas × valor/hora × 48 semanas. Representa el valor de ese tiempo, no un ahorro garantizado.", "E se a parte repetitiva não precisasse ocupar tanto espaço no seu dia?": "¿Y si la parte repetitiva no tuviera que ocupar tanto espacio en su día?", "Veja como o DocFlow entra na sua rotina.": "Vea cómo DocFlow entra en su rutina.",
      "A mesma planta. Dois processos.": "La misma planta. Dos procesos.", "Veja a diferença nas cotas": "Vea la diferencia en las cotas", "na prática.": "en la práctica.", "Quanto tempo você levaria para cotar uma planta como essa?": "¿Cuánto tardaría en acotar una planta como esta?", "Compare o processo manual com a execução usando o DocFlow.": "Compare el proceso manual con la ejecución usando DocFlow.", "Pausar vídeos": "Pausar videos", "Do início": "Desde el inicio", "Processo manual": "Proceso manual", "Cotas feitas à mão": "Cotas hechas a mano", "Vídeo acelerado": "Video acelerado", "Selecionar, posicionar e repetir em cada ambiente.": "Seleccionar, posicionar y repetir en cada ambiente.", "Tempo no cronômetro": "Tiempo en el cronómetro", "Processo com DocFlow": "Proceso con DocFlow", "Cotas com poucos cliques": "Cotas con pocos clics", "Executar o comando e conferir as cotas prontas no modelo.": "Ejecute el comando y revise las cotas listas en el modelo.", "Ver as outras ferramentas": "Ver las otras herramientas",
      "Dentro do Revit": "Dentro de Revit", "Veja a documentação do seu projeto ganhar forma no Revit.": "Vea cómo la documentación de su proyecto cobra forma en Revit.", "Escolha uma ferramenta e acompanhe o DocFlow executando cada etapa no projeto.": "Elija una herramienta y siga a DocFlow ejecutando cada etapa en el proyecto.", "Um comando. Uma tarefa resolvida.": "Un comando. Una tarea resuelta.", "Você clica uma vez...": "Hace clic una vez...", "e tudo sai pronto.": "y todo queda listo.", "Arraste para o lado ou use as setas do teclado.": "Arrastre hacia un lado o use las flechas del teclado.",
      "Recursos incluídos": "Recursos incluidos", "As ferramentas que acompanham sua documentação.": "Las herramientas que acompañan su documentación.", "Das primeiras cotas à montagem das pranchas. Um conjunto de comandos para diferentes etapas do seu projeto, na mesma aba do Revit.": "Desde las primeras cotas hasta el montaje de láminas. Un conjunto de comandos para diferentes etapas de su proyecto, en la misma pestaña de Revit.", "Paredes externas": "Muros exteriores", "Paredes internas": "Muros interiores", "Paredes por seleção": "Muros por selección", "Paredes em lote": "Muros por lote", "Famílias por região": "Familias por región", "Famílias por ambiente": "Familias por ambiente", "Cotas por ambiente": "Cotas por ambiente", "Cotas de pisos": "Cotas de pisos", "Cotas de forros": "Cotas de techos", "Cotas em cortes": "Cotas en secciones", "Tags de portas": "Etiquetas de puertas", "Tags de janelas": "Etiquetas de ventanas", "Tags de paredes": "Etiquetas de muros", "Tags de ambientes": "Etiquetas de ambientes", "Tags de forros": "Etiquetas de techos", "Nível dos ambientes": "Nivel de los ambientes", "Vistas por ambiente": "Vistas por ambiente", "Gerador de pranchas": "Generador de láminas", "Exportar pranchas": "Exportar láminas", "Configurações de cotas": "Configuración de cotas", "Configurações de tags": "Configuración de etiquetas",
      "Configurável para o seu escritório": "Configurable para su oficina", "Seu padrão de projeto. Seu jeito de documentar.": "Su estándar de proyecto. Su forma de documentar.", "Use os tipos de cotas que já fazem parte do seu projeto, defina os afastamentos e salve suas preferências. A automação segue o padrão que você configura.": "Use los tipos de cotas que ya forman parte de su proyecto, defina las separaciones y guarde sus preferencias. La automatización sigue el estándar que configure.", "Configurações": "Configuración", "Tipos de cotas, afastamentos e perfis salvos no mesmo lugar.": "Tipos de cotas, separaciones y perfiles guardados en un mismo lugar.",
      "Assinatura anual": "Suscripción anual", "Cotas, vistas e pranchas no seu próximo projeto.": "Cotas, vistas y láminas en su próximo proyecto.", "Acesse as ferramentas do DocFlow ARQ e as atualizações durante a assinatura.": "Acceda a las herramientas de DocFlow ARQ y a las actualizaciones durante la suscripción.", "NÃO SOU ALUNO": "NO SOY ALUMNO", "SOU ALUNO BIM CODER": "SOY ALUMNO BIM CODER", "Desconto de lançamento": "Descuento de lanzamiento", "DocFlow ARQ · Anual": "DocFlow ARQ · Anual", "Preço anual regular:": "Precio anual regular:", "preço de lançamento": "precio de lanzamiento", "Ferramentas de cotas, vistas e pranchas": "Herramientas de cotas, vistas y láminas", "Configurações e modelos de pranchas": "Configuraciones y modelos de láminas", "Atualizações durante a assinatura": "Actualizaciones durante la suscripción", "Atendimento DocFlow": "Soporte DocFlow", "7 dias de garantia": "7 días de garantía", "Licença individual · ativação pelo e-mail da compra · compatível com Revit 2025 e 2027": "Licencia individual · activación con el correo de compra · compatible con Revit 2025 y 2027",
      "Teste no seu projeto": "Pruébelo en su proyecto", "Experimente as ferramentas no seu projeto por 7 dias.": "Pruebe las herramientas en su proyecto durante 7 días.", "Instale o DocFlow e experimente as ferramentas de cotas, vistas e pranchas em um projeto seu. Se não fizer sentido para sua rotina, solicite o reembolso dentro do prazo de garantia.": "Instale DocFlow y pruebe las herramientas de cotas, vistas y láminas en uno de sus proyectos. Si no tiene sentido para su rutina, solicite el reembolso dentro del plazo de garantía.", "Perguntas frequentes": "Preguntas frecuentes", "Antes de começar seu próximo projeto.": "Antes de comenzar su próximo proyecto.", "Seu próximo projeto": "Su próximo proyecto", "Dedique mais tempo ao projeto.": "Dedique más tiempo al proyecto.", "Resolva as tarefas repetitivas com poucos cliques.": "Resuelva las tareas repetitivas con pocos clics.", "7 dias de garantia · Revit 2025 e 2027 · suporte em português": "7 días de garantía · Revit 2025 y 2027 · soporte en portugués", "Um produto BIM Coder Tecnologia LTDA": "Un producto de BIM Coder Tecnologia LTDA", "Fechar": "Cerrar", "Prévia interna": "Vista previa interna", "Checkout ainda não conectado": "El checkout aún no está conectado", "O plano já está pronto na página. Falta apenas inserir o link correspondente da Hotmart antes da publicação.": "El plan ya está listo en la página. Solo falta insertar el enlace correspondiente de Hotmart antes de publicar.", "Entendi": "Entendido", "Desconto de lançamento · aluno": "Descuento de lanzamiento · alumno", "Desconto de lançamento para aluno BIM Coder: R$ 300 no primeiro ano. Depois, renovação por R$ 797/ano.": "Descuento de lanzamiento para alumno BIM Coder: R$ 300 en el primer año. Después, la renovación cuesta R$ 797/año.", "Desconto de lançamento de R$ 200 no primeiro ano. Depois, renovação por R$ 797/ano.": "Descuento de lanzamiento de R$ 200 en el primer año. Después, la renovación cuesta R$ 797/año.", "Garantir desconto de aluno — R$ 497": "Obtener descuento de alumno — R$ 497", "Garantir desconto de lançamento — R$ 597": "Obtener descuento de lanzamiento — R$ 597"
    }
  };
  const labels = { pt: { code: "BR", name: "PT" }, en: {
"Ver ferramentas": "See tools", code: "EN", name: "EN" }, es: {
"Ver ferramentas": "Ver herramientas", code: "ES", name: "ES" } };
  const titles = { pt: "DocFlow ARQ | Cotas, vistas e pranchas no Revit", en: "DocFlow ARQ | Dimensions, views, and sheets in Revit", es: "DocFlow ARQ | Cotas, vistas y láminas en Revit" };
  const sourceByTranslation = {};
  Object.keys(copy).forEach((language) => Object.entries(copy[language]).forEach(([pt, translated]) => { sourceByTranslation[translated] = pt; }));
  let language = localStorage.getItem("docflow-language") || "pt";
  if (!labels[language]) language = "pt";
  const normalize = (text) => text.trim();
  const translateTextNode = (node) => {
    const current = normalize(node.nodeValue);
    if (!current) return;
    const source = copy.pt?.[current] ? current : (sourceByTranslation[current] || current);
    const translated = language === "pt" ? source : copy[language]?.[source];
    if (!translated || translated === current) return;
    node.nodeValue = node.nodeValue.replace(current, translated);
  };
  const translateTree = (root = document.body) => {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, { acceptNode(node) { const parent = node.parentElement; return parent && !["SCRIPT", "STYLE"].includes(parent.tagName) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT; } });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(translateTextNode);
  };
  const apply = (nextLanguage) => {
    language = nextLanguage;
    localStorage.setItem("docflow-language", language);
    document.documentElement.lang = language === "pt" ? "pt-BR" : language;
    document.title = titles[language];
    translateTree();
    document.querySelectorAll("[data-language-current]").forEach((item) => item.textContent = labels[language].name);
    document.querySelectorAll(".language-code").forEach((item) => item.textContent = labels[language].code);
    document.querySelectorAll("[data-language]").forEach((button) => button.classList.toggle("is-active", button.dataset.language === language));
    window.dispatchEvent(new CustomEvent("docflow-languagechange", { detail: { language } }));
  };
  document.querySelectorAll("[data-language]").forEach((button) => button.addEventListener("click", () => { apply(button.dataset.language); button.closest("details").removeAttribute("open"); }));
  const observer = new MutationObserver((records) => {
    if (language === "pt") return;
    records.forEach((record) => {
      if (record.type === "characterData") translateTextNode(record.target);
      record.addedNodes.forEach((node) => { if (node.nodeType === Node.TEXT_NODE) translateTextNode(node); else if (node.nodeType === Node.ELEMENT_NODE) translateTree(node); });
    });
  });
  observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  apply(language);
  window.docflowI18n = { apply, get language() { return language; }, translate: translateTree };
})();